name: audio_wave
description: Customizable bar graph(wave graph) with wave animation.
version: 0.0.1
homepage: https://github.com/thruthesky/audio_wave

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
